apiVersion: apps/v1
kind: DemonSet
metadata:
  name: nginxdemonset
spec:
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80