#kubectl label node <ip of node1> environment=test
#kubectl label node <ip of node2> environment=prod
#based on the nodelabel select the node selector

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
    nodeSelector:
    environment: test
      containers:
        - name: myapp
          image: nayana000/pythonapp:v1
          ports:
            - containerPort: 8080