apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  clusterIP: None
  selector:
    app: ipapp
  ports:
    - name: http
      port: 30000 # service port
      targetPort: 8080 # application port