#service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa

---

#tocken
apiVersion: v1
kind: Secret
metadata:
  name: mysatocken
  annotations:
    kubernetes.io/service-account.name: "mysa"
type: kubernetes.io/service-account-token